config/routes.rb
Rails.application.routes.draw do
  resources :collaborators
  resources :wikis
  resources :charges, only: [:new, :create]
  devise_for :users

  get 'welcome/about' => 'welcome#about'
  root 'welcome#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
	def self.default
		return 15_00
	end

	def self.sum
		return 15.00
	end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
	belongs_to :user
	belongs_to :wiki
end

app/models/controller.rb
class Controller < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :wikis
	has_many :collaborators
	has_many :collaborator_wikis, through: :collaborators, source: :wiki
	
	enum role: [:standard, :premium, :admin]
	after_initialize do
		self.role ||= :standard
	end
	attr_accessor :login

	# Include default devise modules. Others available are:
	# :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]

	#Make sure that someone's username != someone's email
	validate :validate_username

	def validate_username
		if User.where(email: username).exists?
			errors.add(:username, :invalid)
		end
	end

	def self.admin?
		self.role == :admin
	end

	def self.standard?
		self.role == :standard
	end

	def self.premium?
		self.role == :premium
	end

	def edit
		self.downgrade!
	end

	#Overwrite Devise's find_for_database_authentication method to change the behaviour of the login action. 
	def self.find_first_by_auth_conditions(warden_conditions)
		conditions = warden_conditions.dup
		if login = conditions.delete(:login)
			where(conditions).where(["username = :value OR lower(email) = lower(:value)", {:value => login}]).first
		else
			if conditions[:username].nil?
				where(conditions).first
			else
				where(username: conditions[:username]).first
			end
		end
	end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 10}, presence: true
  validates :user, presence: true
  scope :visible_to, -> (user) {user ? all : where(private: false)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation, :remember_me)}
    devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:login, :username, :email, :password, :remember_me)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:username, :email, :password, :password_confirmation, :current_password)}
  end
  
  private 
  def user_not_authorized
		flash[:alert] = "Access denied."
    #Send to page they came from or root page.
  	redirect_to(request.referrer || root_path)
	end
end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
		@stripe_btn_data = {
			key: "#{Rails.configuration.stripe[:publishable_key]}",
			description: "BigMoney Membership - #{current_user.username}",
			amount: Amount.default
		}
	end

	def create
		#creates a stripe customer object for associating with the charge
		customer = Stripe::Customer.create(
			email: current_user.email,
			card: params[:stripeToken]
		)

		charge = Stripe::Charge.create(
			customer: customer.id, #not the user id
			amount: Amount.default,
			description: "Premium Membership - #{current_user.email}",
			currency: 'usd'
		)

		#Update the users role after payment goes through 
		current_user.update_attribute(:role, "premium")

		flash[:notice] = "Thanks for all the money, #{current_user.username}! Feel free to pay me again!"
		redirect_to root_path

		#Catch and display card errors
	rescue Stripe::CardError => e  
		flash[:alert] = e.message
		redirect_to new_charge_path
	end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
  	Collaborator.create(wiki_id: params[:wiki_id], user_id: params[:user_id])
  	redirect_to :back
  end

  def new
  	@collaborator = Collaborator.new.find_by(user_id: user.id, wiki_id: params[:wiki_id])
  end

  def index
  	@wiki = Wiki.find(params[:wiki_id])
  	@users = User.all
  end

  def destroy
  	Collaborator.find_by(user_id: params[:id], wiki_id: params[:wiki_id]).delete
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def edit
		@user = current_user
		@user.update_attributes(role: 'standard')

		if @user.save
			flash[:notice] = "Account downgraded to 'Standard'"
			redirect_to wikis_path

			#make wikis public when user account is downgraded
			@user.wikis.each do |wiki|
				wiki.update_attribute(:private, false)
			end
		else
			flash[:alert] = "Could not downgrade your account."
		end
	end

	def index
		@users = User.all  
	end

	def show
		@user = User.find(params[:id])
		authorize @user
	end

	def destroy
		@user = User.find(params[:id])

		if user.destroy
			flash[:notice] = "User deleted."
			redirect_to users_path
		else
			flash[:alert] = "Failed to delete user."
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
      @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])

    unless !@wiki.private || current_user.admin? || current_user.premium?
      flash[:alert] = "You must be a premium member to view private wikis."
      redirect_to wikis_path
    end
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user = current_user
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again later."
      render :new
    end
  end

  def edit
      @wiki = Wiki.find(params[:id])
      authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error saving the wiki. Please try again later."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" has been deleted."
      redirect_to wikis_path
    else
      flash[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		Redcarpet::Markdown.new(Redcarpet::Render::HTML,
			no_intra_emphasis: true,
			fenced_code_blocks: true,
			disable_indented_code_blocks: true,
			quote: true,
			underline: true,
			highlight: true
			).render(text).html_safe
	end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
	<article>
		<% if flash[:error].present? %>
			<div id="error_explanation">
				<p><%= flash[:error] %></p>
			</div>
		<% end %>
		<p><strong>Premium Membership</strong></p>
		<label class="amount">
			<span><%= "Amount: $ #{Amount.sum}" %></span>
		</label>
	</article>

	<h4>Click the button!</h4>
	<script class='stripe-button' 
			src="https://checkout.stripe.com/checkout.js" 
			data-key="<%= @stripe_btn_data[:key] %>" 
			data-amount=<%= @stripe_btn_data[:amount]%> 
			data-description="<%= @stripe_btn_data[:description] %>" >
	</script>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/collaborators/index.html.erb
<h1>Add Collaborators to <%= @wiki.title %> wiki</h1>

<table class="table table-bordered">
  <tbody>
<% @users.each do |user| %>
      <tr>
        <td class="col-md-4"><%= "User: #{user.email}" %></td>
        <td class="col-md-1">
          <% if Collaborator.find_by(user_id: user.id, wiki_id: params[:wiki_id]) %>
          <div>
            <input type="checkbox" class="collaborator-box" checked=true />
            <a href="/collaborators/<%= user.id %>?wiki_id= <%= params[:wiki_id]%>" data-method="DELETE"> </a>
          </div>
          <% else %>
            <div>
              <input type="checkbox" class="collaborator-box"/>
              <a href="/collaborators?user_id=<%= user.id %>&wiki_id= <%= params[:wiki_id]%>" data-method="POST"></a>
            </div>
          <% end %>
        </td>
      </tr>
    </div>

<% end %>
</tbody>
</table>

<script>
  $(".collaborator-box").click(function(){
    console.log($(this).parent().find("a").click());
  })
</script>

app/views/collaborators/new.html.erb
<%= form_for @collaborator do |f| %>
  <div class="form-group">
    <%= f.number_field :wiki_id %>
    <%= f.number_field :user_id, class: 'form-control', placeholder: "Enter user_id" %>
    <%= f.submit %>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewpoer" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", welcome_about_path %></li> 
			<li><%= link_to "Wikis", wikis_path %></li>
			<% if current_user && current_user.premium? %>
				<li><%= link_to "Downgrade", edit_user_registration_path %></li>
			<% elsif current_user && current_user.standard? %>
				<li><%= link_to "Upgrade", edit_user_registration_path %></li>
			<% end %>
			<div class="pull-right user-info">
				<% if user_signed_in? %>
					<% if current_user.username? %>
						Signed in as: <strong><%= current_user.username %></strong> |
					<% else %>
						Signed in as: <strong><%= current_user.email %></strong> |
					<% end %>
					<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
				<% else %>
					<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
				<% end %>
			</div>
		</ul>

		<% if flash[:notice] %>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= flash[:notice] %>
			</div>
		<% elsif flash.now[:alert] %>
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= flash.now[:alert] %>
			</div>
		<% elsif flash[:alert] %>
			<div class="alert alert-warning">
				<button type="button" class="close" data-dismiss-"alert">&times;</button>
				<%= flash[:alert] %>
			</div>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/welcome/about.html.erb
<h1>About</h1>
<p id="description">Create public and private markdown-based wikis</p>

app/views/welcome/index.html.erb
<h1>Home</h1>
<p id="description">Welcome to Blocipedia</p>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
	</div>
	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, class: 'form-control', placeholder: "Enter wiki body" %>
	</div>
	<div class="form-group">
		<% if current_user.admin? || current_user.premium? %>
			<div class="checkbox">
				<%= f.label :private, class: 'checkbox' do %>
					<%= f.check_box :private %>Private Wiki?
				<% end %>
			</div>
		<% end %>
	</div>
	<div class="form-group">
		<%= f.submit "Save", class: 'btn btn-success' %>
	</div>
<% end %>

app/views/wikis/delete.html.erb
<h1>Wikis#delete</h1>
<p>Find me in app/views/wikis/delete.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit wiki</h1>
<%= render partial: 'form', locals: {wiki: @wiki} %>
<% if current_user && (current_user.admin? || current_user.premium?) %>
    <div class="form-group">
       	<%= link_to "Manage Collaborators", collaborators_path(wiki_id: @wiki.id) %>
    </div>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<div class="row">
	<div class="col-md-4">
		<% @wikis.each do |wiki| %>
			<p><%= link_to wiki.title, wiki %></p>
		<% end %>
	</div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<%= render partial: 'form', locals: {wiki: @wiki} %>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>
<div class="row">
	<div class="col-md-8">
		<p><%= markdown(@wiki.body) %></p>
		<% if @wiki.user.username %>
			<p><%= "User: #{@wiki.user.username}" %></p>
		<% else %>
			<p><%= "User: #{@wiki.user.email}" %></p>
		<% end %>
	</div>
	<% if current_user && policy(@wiki).admin_or_owner? %>
		<div class="col-md-4">
			<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
			<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
		</div>
	<% end %>
</div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>